# Generated by Django 4.2.6 on 2023-11-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_day', '0003_userprofile_families'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='families',
            field=models.ManyToManyField(blank=True, to='laundry_day.family'),
        ),
    ]
