# Generated by Django 4.2.6 on 2023-11-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_day', '0004_alter_userprofile_families'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='family',
            table='Family',
        ),
    ]
