# Generated by Django 4.2.6 on 2023-11-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_day', '0005_alter_family_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='laundryrequests',
            table='Laundry_Requests',
        ),
    ]
